/* embed.c — generate embedded_runtime.h from the runtime sources.
 * Produces byte arrays so cmmc can write the runtime to a temp dir at
 * build time, making the compiler a single self-contained binary. */
#include <stdio.h>
#include <stdlib.h>

static void dump(FILE *out, const char *path, const char *sym){
    FILE *f=fopen(path,"rb");
    if(!f){ fprintf(stderr,"embed: cannot open %s\n",path); exit(1); }
    fprintf(out,"static const unsigned char %s[] = {\n",sym);
    int c, col=0; long n=0;
    while((c=fgetc(f))!=EOF){
        fprintf(out,"%d,",c); n++;
        if(++col==20){ fputc('\n',out); col=0; }
    }
    fprintf(out,"\n};\nstatic const unsigned long %s_len = %ldUL;\n\n",sym,n);
    fclose(f);
}

int main(int argc, char **argv){
    if(argc!=4){ fprintf(stderr,"usage: embed runtime.h runtime.c out.h\n"); return 2; }
    FILE *out=fopen(argv[3],"w");
    if(!out){ fprintf(stderr,"embed: cannot write %s\n",argv[3]); return 1; }
    fprintf(out,"/* Auto-generated by embed.c. Do not edit. */\n");
    fprintf(out,"#ifndef CMM_EMBEDDED_RUNTIME_H\n#define CMM_EMBEDDED_RUNTIME_H\n\n");
    dump(out, argv[1], "RUNTIME_H");
    dump(out, argv[2], "RUNTIME_C");
    fprintf(out,"#endif\n");
    fclose(out);
    return 0;
}
