"""C code generation for the cmm language.

Takes the analyzed program (dict classname -> Module, plus the entry class) and
emits a single C99 translation unit that links against the cmm runtime
(cmm_runtime.c / cmm_runtime.h).

Design (see project notes):
  * One uniform runtime value type `CmmValue`; everything is dynamically
    tagged at runtime, statically typed by the analyzer for dispatch.
  * Each user class -> a `<Class>_new()` constructor returning a CmmValue
    object whose fields are initialised to their declared typed-empty values,
    plus one C function per method: `<Class>_<method>(CmmValue self, ...)`.
  * `@name`  -> `self.obj->fields[INDEX]`.
  * Operators -> runtime calls (cmm_add, cmm_lt, ...). One operator per
    expression is guaranteed by the parser.
  * Calls dispatched by the analyzer-resolved `Call.kind`.
  * `run` evaluates its call on a worker thread; `wait` joins and yields the
    result. A per-run-site thunk struct + thread function is generated.
  * `use @a, @b { ... }` locks the named class-variable mutexes in ascending
    field-index order and unlocks in reverse.
"""

from . import ast
from . import types as T


C_KEYWORDS = {
    "auto", "break", "case", "char", "const", "continue", "default", "do",
    "double", "else", "enum", "extern", "float", "for", "goto", "if", "int",
    "long", "register", "return", "short", "signed", "sizeof", "static",
    "struct", "switch", "typedef", "union", "unsigned", "void", "volatile",
    "while", "self", "restrict", "inline", "_Bool",
}


def cident(name):
    """Make a cmm identifier safe to use as a C identifier."""
    if name in C_KEYWORDS:
        return "lv_" + name
    return name


def cstring(s):
    out = []
    for ch in s:
        if ch == '\\':
            out.append('\\\\')
        elif ch == '"':
            out.append('\\"')
        elif ch == '\n':
            out.append('\\n')
        elif ch == '\r':
            out.append('\\r')
        elif ch == '\t':
            out.append('\\t')
        elif 32 <= ord(ch) < 127:
            out.append(ch)
        else:
            # emit UTF-8 bytes as octal escapes so the C literal is portable
            for b in ch.encode("utf-8"):
                out.append("\\%03o" % b)
    return '"' + "".join(out) + '"'


class CodeGen:
    def __init__(self, program, entry, debug=False):
        self.program = program          # classname -> Module
        self.entry = entry
        self.debug = debug
        self.cur_class = None
        self.classes = list(program.values())
        self.class_id = {m.classname: i for i, m in enumerate(self.classes)}
        self.thunks = []                # top-level thunk struct+fn snippets
        self.tmp = 0
        self.lines = []                 # output buffer

    # ---- utilities --------------------------------------------------------
    def new_tmp(self, prefix="__t"):
        self.tmp += 1
        return f"{prefix}{self.tmp}"

    def emit(self, s=""):
        self.lines.append(s)

    # ---- top-level --------------------------------------------------------
    def generate(self):
        self.emit('/* Generated by cmmc. Do not edit. */')
        self.emit('#include "cmm_runtime.h"')
        self.emit("")
        # class id constants
        for m in self.classes:
            self.emit(f"#define CLASS_{cident(m.classname)} {self.class_id[m.classname]}")
        self.emit("")
        # forward declarations
        for m in self.classes:
            self.emit(f"static CmmValue {cident(m.classname)}_new(void);")
            for fn in m.functions:
                self.emit(self._proto(m, fn) + ";")
        self.emit("")

        # method + constructor bodies (collect thunks along the way)
        bodies = []
        for m in self.classes:
            bodies.append(self._gen_constructor(m))
            for fn in m.functions:
                bodies.append(self._gen_function(m, fn))

        # thunks must precede the functions that reference them
        for t in self.thunks:
            self.emit(t)
        if self.thunks:
            self.emit("")
        for b in bodies:
            self.emit(b)
            self.emit("")

        # entry point
        self._gen_main()
        return "\n".join(self.lines) + "\n"

    def _proto(self, m, fn):
        params = ["CmmValue self"]
        for p in fn.params:
            params.append("CmmValue " + cident(p.name))
        return f"static CmmValue {cident(m.classname)}_{cident(fn.name)}(" + ", ".join(params) + ")"

    # ---- constructor ------------------------------------------------------
    def _typed_empty(self, tref):
        n = tref.name
        if n == "Int":
            return "cmm_int(0)"
        if n == "Float":
            return "cmm_float(0)"
        if n == "Bool":
            return "cmm_bool(0)"
        if n == "String":
            return 'cmm_str("")'
        if n == "List":
            return "cmm_new_list()"
        if n == "Dict":
            return "cmm_new_dict()"
        # Data, user classes, Socket, etc. -> universal empty
        return "cmm_empty()"

    def _gen_constructor(self, m):
        self.cur_class = m
        cls = cident(m.classname)
        nf = len(m.variables)
        out = []
        out.append(f"static CmmValue {cls}_new(void) {{")
        out.append(f"    CmmValue self = cmm_object_value(cmm_new_object(CLASS_{cls}, {nf}, 0));")
        for i, v in enumerate(m.variables):
            out.append(f"    self.obj->fields[{i}] = {self._typed_empty(v.type)};")
        out.append("    return self;")
        out.append("}")
        return "\n".join(out)

    # ---- function bodies --------------------------------------------------
    def _collect_locals(self, fn):
        """Find every local name assigned/declared anywhere in the body so we
        can declare them up front (cmm locals are function-scoped)."""
        names = []
        seen = set()
        params = {p.name for p in fn.params}

        def add(n):
            if n not in seen and n not in params:
                seen.add(n)
                names.append(n)

        def walk(stmts):
            for s in stmts:
                if isinstance(s, ast.Assign) and isinstance(s.target, ast.Name):
                    add(s.target.name)
                elif isinstance(s, ast.EmptyDecl):
                    add(s.name)
                elif isinstance(s, ast.For):
                    add(s.var)
                    walk(s.body)
                elif isinstance(s, ast.If):
                    walk(s.then)
                    if s.otherwise:
                        walk(s.otherwise)
                elif isinstance(s, ast.While):
                    walk(s.body)
                elif isinstance(s, ast.UseLock):
                    walk(s.body)
        walk(fn.body)
        return names

    def _gen_function(self, m, fn):
        self.cur_class = m
        self.lock_stack = []          # active use-lock arrays, outer..inner
        out = [self._proto(m, fn) + " {"]
        out.append("    cmm_frame_enter();")
        # declare locals
        for n in self._collect_locals(fn):
            out.append(f"    CmmValue {cident(n)} = cmm_empty();")
        body = []
        for s in fn.body:
            self.gen_stmt(s, body, 1)
        out.extend(body)
        # guarantee a return for value methods / fallthrough
        out.append("    return cmm_frame_leave(cmm_empty());")
        out.append("}")
        return "\n".join(out)

    # ---- statements -------------------------------------------------------
    def gen_stmt(self, s, out, ind):
        pad = "    " * ind
        if self.debug and self.cur_class is not None:
            ln = getattr(s, "line", 0)
            if ln:
                out.append(f'#line {ln} "{self.cur_class.classname}.cmm"')
        name = "stmt_" + type(s).__name__
        fn = getattr(self, name, None)
        if fn is None:
            raise NotImplementedError(f"codegen for {type(s).__name__}")
        fn(s, out, ind, pad)

    def stmt_Assign(self, s, out, ind, pad):
        setup = []
        val = self.gen_expr(s.value, setup)
        out.extend(pad + ln for ln in setup)
        tgt = s.target
        if isinstance(tgt, ast.Name):
            out.append(f"{pad}{cident(tgt.name)} = {val};")
        elif isinstance(tgt, ast.ClassVarRef):
            idx = self.cur_class.var_index[tgt.name]
            out.append(f"{pad}cmm_field_set(self, {idx}, {val});")
        elif isinstance(tgt, ast.Index):
            isetup = []
            cont = self.gen_expr(tgt.target, isetup)
            idx = self.gen_expr(tgt.index, isetup)
            out.extend(pad + ln for ln in isetup)
            out.append(f"{pad}cmm_index_set({cont}, {idx}, {val});")
        else:
            raise NotImplementedError("assign target")

    def stmt_EmptyDecl(self, s, out, ind, pad):
        out.append(f"{pad}{cident(s.name)} = {self._typed_empty(s.type)};")

    def stmt_IncDec(self, s, out, ind, pad):
        setup = []
        ref = self.gen_expr(s.target, setup)
        out.extend(pad + ln for ln in setup)
        op = "cmm_add" if s.op == "++" else "cmm_sub"
        if isinstance(s.target, ast.ClassVarRef):
            idx = self.cur_class.var_index[s.target.name]
            out.append(f"{pad}cmm_field_set(self, {idx}, {op}(self.obj->fields[{idx}], cmm_int(1)));")
        else:
            out.append(f"{pad}{ref} = {op}({ref}, cmm_int(1));")

    def stmt_ExprStmt(self, s, out, ind, pad):
        setup = []
        e = self.gen_expr(s.expr, setup)
        out.extend(pad + ln for ln in setup)
        out.append(f"{pad}(void)({e});")

    def _emit_unlocks(self, out, pad):
        # release any locks currently held, innermost (last acquired) first
        for lkvar, count in reversed(getattr(self, "lock_stack", [])):
            out.append(f"{pad}cmm_object_unlock(self.obj, {lkvar}, {count});")

    def stmt_Return(self, s, out, ind, pad):
        if s.value is None:
            self._emit_unlocks(out, pad)
            out.append(f"{pad}return cmm_frame_leave(cmm_empty());")
            return
        setup = []
        v = self.gen_expr(s.value, setup)
        out.extend(pad + ln for ln in setup)
        # capture the return value before unlocking (it may read locked state)
        rv = self.new_tmp("__ret")
        out.append(f"{pad}CmmValue {rv} = {v};")
        self._emit_unlocks(out, pad)
        out.append(f"{pad}return cmm_frame_leave({rv});")

    def stmt_If(self, s, out, ind, pad):
        setup = []
        cond = self.gen_expr(s.cond, setup)
        out.extend(pad + ln for ln in setup)
        out.append(f"{pad}if (cmm_truthy({cond})) {{")
        for st in s.then:
            self.gen_stmt(st, out, ind + 1)
        if s.otherwise:
            out.append(f"{pad}}} else {{")
            for st in s.otherwise:
                self.gen_stmt(st, out, ind + 1)
        out.append(f"{pad}}}")

    def stmt_While(self, s, out, ind, pad):
        # condition may need setup each iteration -> recompute inside loop
        out.append(f"{pad}for (;;) {{")
        setup = []
        cond = self.gen_expr(s.cond, setup)
        inner = "    " * (ind + 1)
        out.extend(inner + ln for ln in setup)
        out.append(f"{inner}if (!cmm_truthy({cond})) break;")
        for st in s.body:
            self.gen_stmt(st, out, ind + 1)
        out.append(f"{pad}}}")

    def stmt_For(self, s, out, ind, pad):
        setup = []
        it = self.gen_expr(s.iterable, setup)
        out.extend(pad + ln for ln in setup)
        itv = self.new_tmp("__it")
        nv = self.new_tmp("__n")
        iv = self.new_tmp("__i")
        out.append(f"{pad}CmmValue {itv} = {it};")
        out.append(f"{pad}size_t {nv} = cmm_iter_count({itv});")
        out.append(f"{pad}for (size_t {iv} = 0; {iv} < {nv}; {iv}++) {{")
        inner = "    " * (ind + 1)
        out.append(f"{inner}{cident(s.var)} = cmm_iter_at({itv}, {iv});")
        for st in s.body:
            self.gen_stmt(st, out, ind + 1)
        out.append(f"{pad}}}")

    def stmt_UseLock(self, s, out, ind, pad):
        idxs = sorted(self.cur_class.var_index[n] for n in s.vars)
        lk = self.new_tmp("__lk")
        out.append(f"{pad}{{")
        inner = "    " * (ind + 1)
        arr = ", ".join(str(i) for i in idxs)
        out.append(f"{inner}int {lk}[] = {{ {arr} }};")
        out.append(f"{inner}cmm_object_lock(self.obj, {lk}, {len(idxs)});")
        self.lock_stack.append((lk, len(idxs)))
        for st in s.body:
            self.gen_stmt(st, out, ind + 1)
        self.lock_stack.pop()
        out.append(f"{inner}cmm_object_unlock(self.obj, {lk}, {len(idxs)});")
        out.append(f"{pad}}}")

    # ---- expressions ------------------------------------------------------
    def gen_expr(self, e, setup):
        name = "expr_" + type(e).__name__
        fn = getattr(self, name, None)
        if fn is None:
            raise NotImplementedError(f"codegen for expr {type(e).__name__}")
        return fn(e, setup)

    def expr_IntLit(self, e, setup):    return f"cmm_int({e.value})"
    def expr_FloatLit(self, e, setup):  return f"cmm_float({e.value!r})"
    def expr_StringLit(self, e, setup): return f"cmm_str({cstring(e.value)})"
    def expr_BoolLit(self, e, setup):   return f"cmm_bool({1 if e.value else 0})"

    def expr_Name(self, e, setup):
        return cident(e.name)

    def expr_ClassVarRef(self, e, setup):
        idx = self.cur_class.var_index[e.name]
        return f"self.obj->fields[{idx}]"

    def expr_ListLit(self, e, setup):
        tmp = self.new_tmp("__list")
        setup.append(f"CmmValue {tmp} = cmm_new_list();")
        for it in e.items:
            v = self.gen_expr(it, setup)
            setup.append(f"cmm_list_add({tmp}, {v});")
        return tmp

    def expr_DictLit(self, e, setup):
        tmp = self.new_tmp("__dict")
        setup.append(f"CmmValue {tmp} = cmm_new_dict();")
        for k, v in zip(e.keys, e.values):
            ck = self.gen_expr(k, setup)
            cv = self.gen_expr(v, setup)
            setup.append(f"cmm_dict_set({tmp}, {ck}, {cv});")
        return tmp

    OPS = {
        "+": "cmm_add", "-": "cmm_sub", "*": "cmm_mul", "/": "cmm_div",
        "%": "cmm_mod", "==": "cmm_eq", "!=": "cmm_ne", "<": "cmm_lt",
        "<=": "cmm_le", ">": "cmm_gt", ">=": "cmm_ge",
        "and": "cmm_and", "or": "cmm_or",
    }

    def expr_Binary(self, e, setup):
        l = self.gen_expr(e.left, setup)
        r = self.gen_expr(e.right, setup)
        fn = self.OPS[e.op]
        return f"{fn}({l}, {r})"

    def expr_Unary(self, e, setup):
        v = self.gen_expr(e.operand, setup)
        if e.op == "not":
            return f"cmm_not({v})"
        return f"cmm_neg({v})"

    def expr_EmptyCheck(self, e, setup):
        v = self.gen_expr(e.operand, setup)
        return f"cmm_bool(cmm_is_empty({v}))"

    def expr_Index(self, e, setup):
        t = self.gen_expr(e.target, setup)
        i = self.gen_expr(e.index, setup)
        return f"cmm_index_get({t}, {i})"

    def expr_Member(self, e, setup):
        # bare Data member access -> dict get by field name
        t = self.gen_expr(e.target, setup)
        return f'cmm_data_get({t}, cmm_str({cstring(e.name)}))'

    def _call_expr(self, call, recv_str, arg_strs):
        """Render a resolved Call to a C expression given pre-rendered
        receiver (or None) and argument strings."""
        kind = call.kind
        if kind == "ctor":
            return f"{cident(call.target_class)}_new()"
        if kind == "self_method":
            args = ", ".join(["self"] + arg_strs)
            return f"{cident(call.target_class)}_{cident(call.method)}({args})"
        if kind == "method":
            args = ", ".join([recv_str] + arg_strs)
            return f"{cident(call.target_class)}_{cident(call.method)}({args})"
        if kind == "static":
            recv = f"{cident(call.target_class)}_new()"
            args = ", ".join([recv] + arg_strs)
            return f"{cident(call.target_class)}_{cident(call.method)}({args})"
        if kind == "native":
            cfn = T.NAMESPACE_METHODS[(call.target_class, call.method)][0]
            return f"{cfn}(" + ", ".join(arg_strs) + ")"
        if kind == "value_method":
            cfn = T.VALUE_METHODS[call.target_class][call.method][0]
            args = ", ".join([recv_str] + arg_strs)
            return f"{cfn}({args})"
        raise NotImplementedError(f"call kind {kind!r}")

    def _render_call(self, call, setup):
        """Render a normal (synchronous) call site, returning a C expr."""
        recv_str = None
        if call.kind in ("method", "value_method"):
            recv_str = self.gen_expr(call.callee.target, setup)
        arg_strs = [self.gen_expr(a, setup) for a in call.args]
        return self._call_expr(call, recv_str, arg_strs)

    def expr_Call(self, e, setup):
        return self._render_call(e, setup)

    def expr_RunExpr(self, e, setup):
        """Evaluate the call on a worker thread; return a Job value."""
        call = e.call
        # Evaluate receiver + args at the run site (captured by value), then
        # run the call body in a generated thread function.
        recv_str = None
        if call.kind in ("method", "value_method"):
            recv_str = self.gen_expr(call.callee.target, setup)
        arg_strs = [self.gen_expr(a, setup) for a in call.args]

        n = len(self.thunks)
        struct = f"__Thunk{n}"
        fields = []
        thunk_recv = None
        thunk_args = []
        if recv_str is not None:
            fields.append("    CmmValue recv;")
            thunk_recv = "th->recv"
        if call.kind in ("self_method",):
            fields.append("    CmmValue self;")
        for i, _ in enumerate(arg_strs):
            fields.append(f"    CmmValue a{i};")
            thunk_args.append(f"th->a{i}")
        fields.append("    CmmJob *job;")

        body_call = self._call_expr(call, thunk_recv, thunk_args)
        # self_method inside thunk uses th->self instead of the ambient self
        if call.kind == "self_method":
            body_call = body_call.replace("(self,", "(th->self,", 1)
            body_call = body_call.replace("(self)", "(th->self)", 1)

        snippet = []
        snippet.append(f"typedef struct {{")
        snippet.extend(fields)
        snippet.append(f"}} {struct};")
        snippet.append(f"static void *__run{n}(void *p) {{")
        snippet.append(f"    cmm_thread_attach();")
        snippet.append(f"    {struct} *th = ({struct} *)p;")
        snippet.append(f"    th->job->result = {body_call};")
        snippet.append(f"    return (void *)0;")
        snippet.append("}")
        self.thunks.append("\n".join(snippet))

        # run-site setup
        thv = self.new_tmp("__th")
        jbv = self.new_tmp("__jb")
        setup.append(f"{struct} *{thv} = ({struct} *)cmm_alloc(sizeof({struct}));")
        if recv_str is not None:
            setup.append(f"{thv}->recv = {recv_str};")
        if call.kind == "self_method":
            setup.append(f"{thv}->self = self;")
        for i, a in enumerate(arg_strs):
            setup.append(f"{thv}->a{i} = {a};")
        setup.append(f"CmmJob *{jbv} = cmm_job_new();")
        setup.append(f"{thv}->job = {jbv};")
        setup.append(f"cmm_thread_start({jbv}, __run{n}, {thv});")
        return f"cmm_job_value({jbv})"

    def expr_WaitExpr(self, e, setup):
        j = self.gen_expr(e.job, setup)
        return f"cmm_job_wait({j})"

    # ---- main -------------------------------------------------------------
    def _gen_main(self):
        cls = cident(self.entry)
        self.emit("int main(int argc, char **argv) {")
        self.emit("    cmm_set_args(argc, argv);")
        self.emit("    cmm_init();")
        self.emit(f"    CmmValue __entry = {cls}_new();")
        # call main() if present, else just construct
        entry_mod = self.program[self.entry]
        has_main = any(f.name == "main" for f in entry_mod.functions)
        if has_main:
            self.emit(f"    {cls}_main(__entry);")
        self.emit("    return 0;")
        self.emit("}")


def generate(program, entry, debug=False):
    return CodeGen(program, entry, debug=debug).generate()
